# Generated by Django 3.1.2 on 2020-10-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=100)),
                ('Data_pulicacao', models.DateField()),
                ('Dala_limite', models.DateField()),
                ('is_new', models.BooleanField(verbose_name=True)),
                ('estado_eoi', models.CharField(choices=[('draft', 'Draft'), ('submetido', 'Submetido'), ('publicado', 'Publicado')], default='available', max_length=32)),
                ('empresa_pulicadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.empresa')),
            ],
        ),
    ]
