# Generated by Django 3.1.2 on 2020-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoi',
            name='Dala_limite',
        ),
        migrations.RemoveField(
            model_name='eoi',
            name='Data_pulicacao',
        ),
        migrations.AlterField(
            model_name='eoi',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
