# Generated by Django 3.1.2 on 2020-10-03 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_auto_20201003_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='data_limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eoi',
            name='data_pulicacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eoi',
            name='data_sessao_QA',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
